let index

let articulation_array = [{"type":"B","sound":"","details":"","entries":[
        "bug", "both", "ball", "bed", "bee", "berry", "birthday", "bath", "boat", "bottle", "beard", "bunny", "busy", "butter", "button", "boy", "bus", "banana", "bird", "bear", "bike", "bag", "bat", "bean", "bone", "robot", "cheeseburger", "baby", "strawberries", "ladybug", "cabin", "neighbor", "about", "above", "bobcat", "cobweb", "goodbye", "habit", "kickball", "marbles", "ribbon", "rabbit", "mailbox", "grabbing", "robin", "rubber", "alphabet", "peek-a-boo", "remember", "crab", "cub", "web", "crib", "ice cube", "job", "door knob", "bib", "club", "grab", "lab", "rib", "rub", "sob", "tube", "shrub", "scrub", "swab", "cab", "cob"
    ]},{"type":"Ch","sound":"tʃ","details":"","entries":[
        "chair", "chat", "chase", "check", "cheese", "cheer", "chest", "chew", "child", "chick", "chin", "cheetah", "checkers", "cherry", "chicken", "children", "cheeseburger", "chili", "chocolate", "chop", "church", "chalk", "cheap", "chipmunk", "choose", "chore", "chapter", "beach ball", "catcher", "crutches", "grandchild", "hatching", "inches", "ketchup", "kitchen", "key chain", "matches", "lunchbox", "marching", "touchdown", "itching", "peaches", "picture", "pitcher", "teacher", "statue", "witches", "reaching", "furniture", "high chair", "temperature", "bleachers", "beach", "couch", "bench", "stretch", "pitch", "catch", "patch", "reach", "reach", "march", "touch", "speech", "wrench", "watch", "witch", "lunch", "stretch", "match", "branch", "ostrich", "switch", "hatch", "ranch", "coach"
    ]},{"type":"D","sound":"","details":"","entries":[
        "dad", "dark", "day", "dime", "do", "done", "dust", "dot", "dive", "dance", "desk", "dish", "dog", "doll", "duck", "door", "dentist", "doctor", "dinner", "down", "dig", "dove", "dear", "does", "date", "medicine", "ladder", "radio", "reading", "wedding", "lady", "spider", "daddy", "feeding", "body", "kindergarten", "birthday", "riding", "Thursday", "baby doll", "calendar", "Canada", "idea", "ready", "shadow", "Tuesday", "louder", "hidden", "hiding", "speeding", "food", "hand", "mud", "bed", "sand", "add", "bad", "bread", "did", "dad", "cried", "glad", "grade", "good", "hide", "kid", "loud", "mad", "read", "wood", "sad", "ride", "red", "played", "side"
    ]},{"type":"F","sound":"","details":"","entries":[
        "face", "farm", "feet", "fur", "phone", "fingers", "fire", "fudge", "food", "five", "fish", "foot", "four", "fork", "forest", "feather", "fist", "fast", "fall", "fossil", "fin", "feed", "fan", "fence", "fox", "elephant", "waffle", "laughing", "office", "headphones", "infant", "gopher", "taffy", "dolphin", "coffee", "breakfast", "campfire", "golfer", "alphabet", "muffin", "sofa", "lifeguard", "traffic", "trophy", "golf ball", "barefoot", "playful", "goldfish", "buffalo", "unfold", "calf", "cuff", "cough", "chief", "elf", "loaf", "leaf", "roof", "thief", "laugh", "wolf", "safe", "chef", "knife", "hoof", "giraffe", "wife", "tough", "sheriff", "stuff", "golf", "cliff", "off", "half", "shelf"
    ]},{"type":"G","sound":"","details":"","entries":[
        "goose", "gate", "gas", "gift", "go", "gulp", "good", "gone", "guess", "give", "ghost", "guitar", "garbage", "goodbye", "goat", "game", "gum", "girl", "golf", "guy", "goal", "gallon", "gold", "garage", "gorilla", "dragon", "luggage", "cougar", "tiger", "eagle", "merry-go-round", "tugboat", "pigpen", "again", "wagon", "sugar", "dugout", "foggy", "magnet", "hamburger", "jogging", "juggle", "pigtail", "magazine", "yoga", "seagull", "alligator", "August", "bigger", "doggy", "bug", "dog", "leg", "bag", "mug", "big", "rag", "pig", "Doug", "frog", "fog", "twig", "slug", "fig", "dig", "log", "hug", "rug", "tag", "wag", "wig", "egg", "tug", "flag", "jug"
    ]},{"type":"H","sound":"","details":"","entries":[
        "hall", "ham", "hand", "hard", "hat", "have", "head", "health", "heart", "height", "help", "high", "hike", "hill", "hint", "hold", "home", "hook", "hop", "hope", "horse", "house", "hug", "hurt", "whole", "beehive", "birdhouse", "doghouse", "doll house", "downhill", "fishhook", "forehead", "groundhog", "lighthouse", "playhouse", "pothole", "redhead", "reheat", "sea horse", "uphill", "White House", "behavior", "buttonhole", "grasshopper", "hula hoop", "Ohio", "Perl Harbor", "pigeonhole", "rehearsal", "rocking horse"
    ]},{"type":"J","sound":"dʒ","details":"","entries":[
        "germs", "jam", "jar", "jaw", "jeans", "jet", "job", "jog", "joke", "joy", "juice", "just", "jump", "Jo", "Jake", "Jess", "Josh", "John", "Joan", "James", "giant", "jelly", "journal", "juggle", "jungle", "agent", "badger", "cages", "edges", "high jump", "magic", "major", "object", "pages", "pigeon", "project", "soldier", "subject", "urgent", "imagine", "educate", "manager", "oxygen", "reject", "longitude", "register", "suggestion", "vegetables", "apologize", "intelligent", "age", "bridge", "cage", "edge", "fudge", "huge", "judge", "page", "ridge", "stage", "wage", "cabbage", "college", "courage", "damage", "garbage", "image", "knowledge", "language", "marriage", "old age", "package", "postage", "sausage", "storage"
    ]},{"type":"K","sound":"","details":"","entries":[
        "can", "cat", "key", "comb", "catch", "coin", "cub", "cone", "carrot", "corn", "cold", "cool", "cop", "cake", "car", "kid", "cave", "coat", "cow", "cut", "cart", "candy", "card", "color", "kite", "racquet", "breakfast", "baking", "chicken", "donkey", "soccer", "sucker", "vacation", "biking", "turkey", "cooking", "weekend", "uncle", "napkin", "bacon", "checkers", "jacket", "pocket", "pumpkin", "raincoat", "taco", "looking", "helicopter", "apricot", "vacuum", "duck", "bike", "lock", "cheek", "hawk", "leak", "rake", "rock", "shake", "music", "book", "back", "pack", "cook", "hike", "sick", "check", "hook", "lick", "neck", "snack", "stick", "truck", "walk", "pick"
    ]},{"type":"L","sound":"","details":"","entries":[
        "leaf", "lamp", "laugh", "leak", "list", "long", "letter", "light", "ladybug", "listen", "lock", "look", "lion", "lemon", "lamb", "lips", "lunch", "lazy", "lake", "lucky", "late", "loose", "leg", "land", "love", "log", "belly", "sailor", "balloon", "alarm", "police", "salad", "pillows", "wallet", "calendar", "family", "wallpaper", "sea lion", "silly", "pilot", "dollar", "Iceland", "olive", "jelly", "shoelace", "elbow", "elephant", "violin", "toilet", "envelope", "ball", "mail", "nail", "seal", "pool", "muscle", "fall", "shell", "tail", "call", "yell", "tall", "heel", "bowl", "bell", "whale", "owl", "hill", "pencil", "towel", "wheel", "hole", "wall", "spell"
    ]},{"type":"M","sound":"","details":"","entries":[
        "mad", "mail", "make", "man", "map", "March", "mask", "match", "math", "May", "meet", "mess", "mice", "might", "milk", "mine", "mix", "Mom", "month", "moon", "moose", "more", "mouse", "mouth", "mud", "human", "lemon", "woman", "family", "camera", "plumber", "tomato", "lawnmower", "hamburger", "submarine", "chimney", "numbers", "drummer", "animal", "salami", "timer", "human", "dreaming", "argument", "Wyoming", "chameleon", "mammal", "image", "famous", "tournament", "clam", "climb", "comb", "cream", "dime", "dream", "flame", "game", "gym", "ham", "home", "hum", "lamb", "Mom", "name", "palm", "plumb", "room", "scream", "slim", "stream", "swim", "team", "thumb", "time"
    ]},{"type":"N","sound":"","details":"","entries":[
        "knees", "nap", "nest", "necklace", "knit", "nurse", "knife", "knock", "know", "nail", "name", "near", "neck", "need", "new", "nice", "night", "nine", "no", "noise", "not", "none", "North", "nose", "note", "bunny", "sunglasses", "peanut", "rainbow", "dinosaur", "banana", "canoe", "doughnut", "pony", "dinner", "many", "any", "honor", "planet", "pony", "rainy", "running", "spinning", "manner", "frowning", "pineapple", "another", "animal", "canary", "China", "brain", "brown", "bun", "can", "cane", "chain", "chin", "clean", "clown", "coin", "cone", "done", "fun", "gone", "green", "lawn", "man", "moon", "phone", "plane", "run", "skin", "spoon", "sun", "train"
    ]},{"type":"NG","sound":"ŋ","details":"","entries":[
        "anger", "anguish", "banging", "Bengal", "England", "English", "finger", "hanger", "hunger", "jingle", "jungle", "longer", "mongoose", "Ping Pong", "singer", "stronger", "Tango", "younger", "bang", "bring", "ding", "dong", "hang", "king", "long", "lung", "ping", "pong", "ring", "sing", "song", "spring", "sting", "string", "strong", "swing", "thing", "tongue", "wrong"
    ]},{"type":"P","sound":"","details":"","entries":[
        "pencil", "party", "pig", "pickle", "pony", "penny", "penguin", "parrot", "pizza", "pirate", "pet", "paint", "peach", "picnic", "piano", "pants", "pie", "parade", "park", "pass", "past", "paid", "pear", "paw", "point", "diaper", "hippo", "apple", "teepee", "wallpaper", "grasshopper", "zipper", "mopping", "super", "octopus", "soapy", "dripping", "teapot", "typewriter", "zookeeper", "copy", "depend", "dustpan", "happy", "paper", "open", "napkin", "napping", "toothpaste", "sleeping", "lamp", "mop", "soup", "ship", "sheep", "tape", "asleep", "rope", "checkup", "envelope", "hoop", "stop", "shop", "ketchup", "cup", "tape", "up", "pipe", "wrap", "trap", "cap", "top", "sweep", "soap", "pop"
    ]},{"type":"Q","sound":"","details":"","entries":[
        "quite", "quick", "quiet", "queen", "quote", "quest", "query", "queue", "quota", "quake", "quilt", "quell", "quasi", "quits", "quirk", "quail", "quill", "quart", "quark", "quack", "quash", "quint", "quant", "quale", "qualm", "qubit", "quire", "quoth", "quiff", "quaff", "quoin", "quern", "quirt", "quoit", "quips", "quins", "quids", "quays", "quaky", "quads"
    ]},{"type":"R","sound":"","details":"","entries":[
        "run", "rice", "rat", "rag", "rake", "red", "wrist", "raisin", "rabbit", "ribbon", "radio", "rocket", "ranch", "rich", "race", "ring", "rain", "rug", "ran", "write", "rip", "recess", "rock", "read", "wrap", "carrot", "bird", "earring", "horse", "iron", "arm", "giraffe", "fork", "shirt", "lizard", "fairy", "pirate", "scissors", "turtle", "camera", "party", "nurse", "worm", "walrus", "park", "syrup", "zero", "corn", "barn", "earth", "four", "bear", "deer", "ear", "tear", "pear", "jar", "alligator", "doctor", "feather", "dollar", "mother", "hammer", "ladder", "car", "chair", "door", "tire", "hair", "beaver", "letter", "kangaroo", "dinosaur", "flower", "father"
    ]},{"type":"R","sound":"","details":"Vocalic","entries":[
        "star", "far", "tarp", "bark", "harp", "art", "cart", "start", "army", "marble", "guard", "garlic", "sparkle", "heart", "tar", "farm", "yard", "tart", "dark", "dart", "card", "yarn", "alarm", "garbage", "market", "cursive", "mixture", "fur", "skirt", "first", "herd", "turn", "learn", "fern", "whisper", "never", "spider", "curds", "butter", "purse", "hurt", "stir", "dirt", "germs", "girl", "turkey", "together", "teacher", "concern", "dinner", "parents", "sheriff", "where", "barefoot", "married", "square", "lair", "mare", "dare", "care", "stare", "share", "fair", "stereo", "marathon", "asparagus", "parrot", "cherry", "dairy", "parachute", "arrow", "hairy", "bury", "caring", "staring", "choir", "flier", "pliers", "umpire", "dryer", "tired", "fire", "campfire", "Ireland", "Irene", "mire", "dire", "liar", "buyer", "hire", "wire", "empire", "briar", "admire", "vampire", "sapphire", "choirs", "ironing", "fireman", "sire", "fear", "steer", "mirror", "year", "hero", "jeer", "hear", "near", "pier", "hearing", "spear", "beard", "cheer", "gear", "disappear", "pioneer", "souvenir", "cashier", "period", "chandelier", "cheering", "cereal", "pyramid", "weird", "cafeteria", "board", "shorts", "shore", "story", "pour", "sports", "sword", "short", "fort", "popcorn", "storm", "thorn", "organ", "morning", "horseshoe", "tornado", "store", "floor", "more", "score", "north", "port", "chore", "orange", "forest"
    ]},{"type":"S","sound":"","details":"","entries":[
        "sit", "soup", "salt", "seal", "sick", "sing", "sun", "save", "seed", "seat", "city", "said", "sad", "sorry", "soap", "sock", "sail", "sour", "sign", "sand", "soft", "seven", "sink", "son", "safe", "baseball", "dancer", "gasoline", "grasshopper", "motorcycle", "fossil", "pencil", "muscle", "beside", "racing", "insect", "recipe", "medicine", "listen", "glasses", "bicycle", "dinosaur", "popsicle", "eraser", "faucet", "messy", "outside", "passing", "whistle", "policeman", "bus", "face", "ice", "grass", "horse", "yes", "address", "office", "purse", "glass", "pass", "voice", "nice", "lips", "class", "dress", "erase", "house", "mouse", "race", "lettuce", "fence", "miss", "juice", "this", "scoop", "scare", "scarf", "skirt", "scout", "scale", "skinny", "scar", "score", "skill", "skip", "skull", "skunk", "scab", "skim", "school", "skin", "skate", "ski", "sky", "slow", "sled", "slacker", "slam", "slab", "slave", "sleigh", "slick", "slit", "slim", "sliver", "sludge", "slug", "slant", "slob", "sleeve", "sleep", "slip", "slide", "slap", "smell", "smoke", "smog", "smear", "smooch", "smudge", "smug", "smock", "smooth", "smack", "smite", "smoky", "smother", "smuggle", "smart", "smash", "small", "smile", "snail", "snack", "snarl", "snatch", "snoop", "snot", "sneak", "snip", "snag", "snob", "snuggle", "snooze", "sniffle", "snoop", "snout", "snorkel", "snicker", "snitch", "snowball", "snort", "snap", "snake", "sneeze", "snow", "snore", "SP - Blends", "spoon", "space", "spy", "spare", "sponge", "sparkle", "spear", "spend", "spin", "spine", "spoon", "space", "spinach", "spa", "spark", "speed", "Spanish", "speech", "spice", "spent", "special", "spider", "speak", "spill", "spell", "sports", "stamp", "step", "stack", "stand", "stay", "steal", "steer", "stitch", "still", "steam", "stone", "stop", "stem", "state", "stick", "sting", "store", "stage", "steak", "start", "stir", "storm", "stuck", "sticker", "star", "stairs", "story", "student", "sweep", "swallow", "swaddle", "swam", "swap", "swarm", "swear", "swat", "sway", "swell", "swept", "swipe", "switch", "sword", "swollen", "swamp", "swim", "swan", "swing", "sweater", "sweet", "sweat"
    ]},{"type":"SH","sound":"ʃ","details":"","entries":[
        "shape", "shirt", "shoe", "ship", "chef", "shot", "shut", "shop", "shy", "share", "shave", "shed", "short", "show", "shine", "shake", "shade", "sharp", "bushes", "dishes", "lotion", "flashlight", "fishing", "ocean", "milkshake", "pushing", "toothbrushes", "addition", "directions", "cushion", "tissue", "sunshine", "eyelashes", "seashore", "machine", "washing", "mushroom", "pet shop", "eruption", "polishing", "Washington", "musician", "dishrag", "brush", "fish", "push", "dish", "cash", "leash", "wash", "trash", "eyelash", "bush", "finish", "ticklish", "polish", "licorice", "splash", "flash", "smash", "fresh", "flush", "rush", "punish", "crash", "rash", "wish", "mash"
    ]},{"type":"T","sound":"","details":"","entries":[
        "teeth", "tire", "toast", "toy", "teacher", "two", "toad", "tiger", "turkey", "taco", "tool", "tooth", "toe", "talk", "towel", "turtle", "team", "take", "tall", "taste", "tub", "touch", "top", "tongue", "time", "button", "guitar", "kitten", "mittens", "potato", "eighteen", "rotten", "hotel", "cotton", "motel", "beauty", "better", "city", "butter", "little", "butterfly", "tomatoe", "biting", "Saturday", "water", "bat", "boat", "cat", "fruit", "goat", "hat", "coat", "light", "nut", "chocolate", "eat", "bite", "cut", "cute", "feet", "get", "sit", "right", "not", "late", "kite", "hot", "hat", "wet", "white"
    ]},{"type":"TH","sound":"ð","details":"Voiced","entries":[
        "that", "than", "the", "they", "their", "them", "these", "they’d", "they’ll", "they’re", "they’ve", "this", "those", "though", "themselves", "therefore", "thee", "thy", "thou", "therein", "feather", "weather", "together", "bathing", "father", "mother", "clothing", "brother", "weatherman", "either", "gather", "other", "worthy", "another", "rather", "soothing", "smoothest", "leather", "tether", "breathe", "lathe", "seethe", "scathe", "teethe", "bathe", "loathe"
    ]},{"type":"TH","sound":"θ","details":"Voiceless","entries":[
        "thorn", "thin", "think", "thunder", "thousand", "thirsty", "thief", "thermometer", "theater", "thermos", "thaw", "thing", "thread", "thoughtful", "three", "thick", "thumb", "thigh", "third", "thank you", "thirty", "thirteen", "therapy", "Thursday", "thimble", "bathtub", "toothache", "toothbrush", "python", "marathon", "healthy", "truthful", "wealthy", "athlete", "bathrobe", "panther", "toothpaste", "birthday", "something", "pathway", "toothpick", "cloth", "moth", "math", "tooth", "fifth", "beneath", "path", "month", "wreath", "booth", "broth", "ninth", "tenth", "breath", "bath", "earth", "mouth", "teeth", "youth", "north", "strength", "south", "oath", "both", "eighth", "hath", "Ruth"
    ]},{"type":"V","sound":"","details":"","entries":[
        "vest", "van", "vine", "vote", "vet", "vase", "vacuum", "valley", "vampire", "vowels", "visor", "visit", "village", "violet", "volcano", "vegetables", "volleyball", "violin", "voice", "vain", "vault", "vanilla", "video", "view", "vent", "driveway", "shaving", "seven", "carnival", "envelope", "beaver", "seventy", "travel", "beverage", "heavy", "driver", "clover", "diver", "cover", "heaven", "advice", "shiver", "river", "mover", "even", "gravy", "invite", "Levi’s", "level", "over", "glove", "sleeve", "olive", "dove", "cave", "love", "five", "beehive", "brave", "drive", "give", "move", "save", "stove", "wave", "above", "forgive", "dive", "remove", "shave", "cursive", "receive", "expensive", "creative", "talkative"
    ]},{"type":"W","sound":"","details":"","entries":[
        "one", "wait", "walk", "wall", "want", "warm", "was", "wash", "watch", "we", "wear", "web", "weeds", "week", "wide", "wife", "wild", "wind", "wings", "wish", "wolf", "words", "work", "world", "worm"
    ]},{"type":"Y","sound":"j","details":"","entries":[
        "use", "used", "yard", "yarn", "yawn", "yawned", "yes", "yell", "yet", "yelled", "you", "you’d", "you’ll", "your", "yours", "young", "youth", "yummy", "yolk", "year", "yam", "kayak", "lawyer", "loyal", "New Year", "New York", "reuse", "reused", "royal", "yo-yo"
    ]},{"type":"Z","sound":"","details":"","entries":[
        "zoo", "zebra", "zero", "zoom", "zebra fish", "zucchini", "zap", "zippy", "zing", "zinc", "Zoe", "zinnia", "Zelda", "zookeeper", "zigzag", "zipper", "zip code", "Zorro", "zeppelin", "Zach", "zapped", "zillion", "zone", "zombie", "zany", "present", "music", "puzzle", "poison", "blizzard", "cheesecake", "cousin", "desert", "wizard", "lizard", "noisy", "fuzzy", "Thursday", "lazy", "magazine", "raisin", "scissors", "razor", "laser", "closet", "daisy", "dozen", "dessert", "freezer", "busy", "cheese", "please", "freeze", "boys", "knees", "nose", "hose", "rose", "babies", "dogs", "cookies", "fingers", "flowers", "sunrise", "bees", "sneeze", "pigs", "keys", "legs", "bugs", "prize", "bananas", "tease", "bears", "exercise"
    ]},{"type":"ZH","sound":"ʒ","details":"","entries":[
        "Jacques", "beige", "luge", "rouge", "Asia", "azure", "closure", "Hoosier", "leisure", "measure", "Persia", "pleasure", "seizure", "treasure", "version", "vision", "amnesia", "aphasia", "aversion", "casual", "Caucasian", "collision", "composure", "conclusion", "confusion", "conversion", "corrosion", "decision", "division", "enclosure", "erosion", "explosion", "inclusion", "measurement", "treasury", "visual", "casually", "disillusion", "measureable", "measuring cup", "measuring tape", "pleasurable", "subdivision", "supervision", "television", "unusual", "usually", "visualize"
    ]}/*,{"type":"Vowels","sound":"","details":"","entries":[

    ]}*/]

let phonetics_array = [
    "B", "Ch", "D", "F", "G", "H", "J", "K", "L", "M", "N", "Ng", "P", "Q", "R", "S", "Sh", "T", "Th (voiced)", "Th (voiceless)", "V", "W", "Y", "Z", "zh"
]

let main_menu = [
    {"name": "Articulation", "color": "#c20000", "onclick": "articulation()", "class": ""},
    {"name": "Language", "color": "#007539", "onclick": "language()", "class": ""},
    {"name": "Phonology", "color": "#b31092", "onclick": "phonology()", "class": ""},
    {"name": "Social", "color": "#d76e00",  "onclick": "social()", "class": ""}
]